
development:
  adapter: postgresql
  encoding: unicode
  database: demo_test_development
  pool: 5
  username: 
  password:
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  database: demo_test_test
  pool: 5
  username: 
  password:
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: production
  pool: 5
  timeout: 5000
